---
- hosts: all
  tasks:
    - name: touch a file
      command: touch /tmp/ansible_ran
    - name: install httpd
      yum:
        name: httpd
        state: installed
    - name: command to yum clean all
      command: yum -y clean all
    
